name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config

      - name: Install Buildozer (stable only)
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython

      - name: FORCE OLD python-for-android
        run: |
          pip install "python-for-android==2023.9.16"

      - name: Fix licenses
        run: yes | sdkmanager --licenses || true

      - name: Build APK
        run: buildozer android debug
